### ISSUE TITLE
[BUG] safe mode screen

### ISSUE THREAD

**Issue by RobbyRotten97** [Aiko-Suzuki/Collection-of-Singiro-Wiki-Issues#1]
**Describe the bug**
So, when i have this mod added and try to open my world as usual it gets stuck in the screen of selecting safemode due conflicting with datapack and even if i select safe mode it keeps stuck in that screen, and tbh idk why.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Aiko-Suzuki** [comment]
Try forge 40.0.46.

here my curseforge test profile.
[Singiro Test Profile.zip](https://github.com/Aiko-Suzuki/Collection-of-Singiro-Wiki-Issues/files/8521868/Singiro.Test.Profile.zip)

**Comment by RobbyRotten97** [comment]
> 

Well, as i load the test profile linked it just give me error loading mods. Mod origions requires forge 40.0.47, apoli the same and calio the same version.

For the issue, could one of the mods i use be provoking the safe mode thing? of origins im using the forge version and the origins classes mod as well for example.

**Comment by Aiko-Suzuki** [comment]
well it's kinda weird since [Medieval Minecraft](https://www.curseforge.com/minecraft/modpacks/medieval-minecraft-new/files/3759093) got it working on 1.18.2 using forge 40.0.46

**Comment by Aiko-Suzuki** [comment]
found it you need to use [Origins-1.18.2-1.3.1.14-unified.jar ](https://www.curseforge.com/minecraft/mc-mods/origins-forge/files/3747134)

**Comment by RobbyRotten97** [comment]
> you need to use [Origins-1.18.2-1.3.1.14-unified.jar ](https://www.curseforge.com/minecraft/mc-mods/origins-forge/files/3747134)

so, using that version in my modpack (including this mod as well) creates me an issue with craftweaks and create and then when i deactivate those two, creates me a problem with the mod comforts twice.

**Comment by Aiko-Suzuki** [comment]
am gonna try to find a fix to make it work with versions higher than 40.0.46.

**Comment by Aiko-Suzuki** [comment]
so i manage to fix the datapack issues for the collection of singiro but other dependencies have the same problem.
![image](https://user-images.githubusercontent.com/42787030/164315313-8330e3ea-6bff-48cb-9b86-5a80248116bc.png)

😕

**Comment by RobbyRotten97** [comment]
> 
I see. well. i tried to go with it again with the new version of your mod that you uploaded a few minutes ago with my modpack  but still the safe mode happens. So nothing much can't be done for now i get?

**Comment by Aiko-Suzuki** [comment]
sadly nothing that we can do

**Comment by RobbyRotten97** [comment]
well, thanks for the help and hope this can be resolves soon. Have a nice day

**Comment by Baggytrousers27** [comment]
The three dependencies (Caelus, Pehkui and Origins) all work fine together in 40.1.0 regardless of datapack incompatibilities. If they only cease functioning when Collection of Singiro is added, wouldn't this mean the issue is with this mod, not the others?

![Dependencies 1](https://user-images.githubusercontent.com/15883796/164453924-dd3d3b58-83d7-497a-b847-c1113a949bcd.PNG)

![Dependencies 2](https://user-images.githubusercontent.com/15883796/164453909-5edc60b2-6245-47d0-a2a5-520c54842d31.PNG)

![2022-04-21_22 01 13](https://user-images.githubusercontent.com/15883796/164453868-f11d97a0-f95d-4a58-a7d6-0d26a86445a9.png)

Also the [debug log (with singiro installed)](https://pastebin.com/Cq7Xej4i) contains this:
[21Apr2022 22:04:39.018] [Worker-Main-20/ERROR] [net.minecraft.tags.TagLoader/]: Couldn't load tag medievalorigins:swords as it is missing following references: minecraft:sinister_sword (from collection-of-singiro-1.18.x-1.0.6.jar), 
	dungeons_gear:rapier (from collection-of-singiro-1.18.x-1.0.6.jar), 
	dungeons_gear:gold_sword (from collection-of-singiro-1.18.x-1.0.6.jar)
[21Apr2022 22:04:40.993] [Render thread/INFO] [net.minecraft.world.item.crafting.Re

[Debug log without](https://pastebin.com/bnd7LG2K) has no mention of tags.

**Comment by Aiko-Suzuki** [comment]
Oh did not check error log mb. Gona work on that then

**Comment by Aiko-Suzuki** [comment]
Gonna keep this open till the end of the week.
